### ISSUE TITLE
Add antialiasing

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/opengl_graphics#47]
This should be supported.

**Comment by xaviershay** [comment]
Since this is first google result for "piston antialias", adding some extra information:

* The method referenced is http://docs.piston.rs/piston/piston/window/struct.WindowSettings.html#method.samples (no docs)
* `piston-examples` sets [samples to `4`](https://github.com/PistonDevelopers/piston-examples/blob/master/src/deform.rs#L14)
* I'm pretty sure this setting only applies to textures, since it's passed through to [https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/lib.rs#L186](`create_main_targets`)
* `imageproc` contains an open issue for drawing antialiased lines: https://github.com/PistonDevelopers/imageproc/issues/97

**Comment by bvssvni** [comment]
@xaviershay It is [multi-sample anti aliasing](https://en.wikipedia.org/wiki/Multisample_anti-aliasing) performed on the GPU. This is done for every pixel in the frame buffer.

**Comment by xaviershay** [comment]
![screen shot 2016-02-21 at 1 38 47 pm](https://cloud.githubusercontent.com/assets/1714/13205611/a517adbc-d8a0-11e5-94c2-c3e1df747285.png)

Side-by-side screenshot of zoomed in polygons, one is `samples(0)`, the others is `samples(4)`. Looks the same to me? Am I setting it up wrong?

Ref: https://github.com/xaviershay/hextest/blob/master/src/main.rs#L152

**Comment by bvssvni** [comment]
Try swapping it with the Glutin backend by changing [this line](https://github.com/xaviershay/hextest/blob/master/src/main.rs#L25) to:

```
pub type GameWindow = PistonWindow;
```

**Comment by xaviershay** [comment]
same results

**Comment by sandeep-datta** [comment]
Sorry for resurrecting an old thread. It seems choosing 4 samples per pixel does not do much (anything?). I noticed smoother edges using 16 samples per pixel. This can be a GPU specific quirk too. I tested this on an NVIDIA GT710.
